app_fsk: compiler fixes and improvements for 18
Includes a number of compiler fixes and improvements for 18:

- included contents of spandsp-sim.h directly, to fix compiler error about file not found
- fixed XML documentation
- fixes mixed code and declarations
- fix unused variable warnings
- changed comments using // to /* */ (per Asterisk style guidelines)
- adds braces around if, else if, else branches (per Asterisk style guidelines)
- fixed whitespace and tabs (per Asterisk style guidelines)
- spelling fixes
- changed standard module declaration to standard extended module declaration

Two compiler errors are still left:
app_fsk_18.c: In function ‘put_bit’:
app_fsk_18.c:193:29: error: operation on ‘user_data->current_bit_no’ may be undefined [-Werror=sequence-point]
  193 |   user_data->current_bit_no = ++user_data->current_bit_no;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app_fsk_18.c: In function ‘fskRX_exec’:
app_fsk_18.c:344:58: error: ‘FSK_FRAME_MODE_8N1_FRAMES’ undeclared (first use in this function); did you mean ‘FSK_FRAME_MODE_7N1_FRAMES’?
  344 |   caller_rx = fsk_rx_init(NULL, &preset_fsk_specs[modem], FSK_FRAME_MODE_8N1_FRAMES, get_bit, in);
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                          FSK_FRAME_MODE_7N1_FRAMES
app_fsk_18.c:344:58: note: each undeclared identifier is reported only once for each function it appears in